ALTER TABLE public.candidates
ADD COLUMN IF NOT EXISTS feedback_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS latest_recommendation DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS latest_feedback_author TEXT,
ADD COLUMN IF NOT EXISTS latest_feedback_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS current_stage_avg_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS current_stage_date DATE,
ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP WITH TIME ZONE;
